packages:
  - apps/*
  - packages/*
allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - "@scarf/scarf"
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
